# Generated by Django 3.0.7 on 2020-06-29 03:32

import API.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=55, validators=[API.validators.min_name_length_validator]),
        ),
    ]
